type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  address: String
  phoneNumber: String
  role: String
}

type Category @table {
  name: String!
  description: String
}

type Product @table {
  name: String!
  price: Float!
  stock: Int!
  createdAt: Timestamp!
  description: String
  imageUrl: String
  category: Category
}

type Order @table {
  user: User!
  orderDate: Timestamp!
  totalAmount: Float!
  status: String!
  shippingAddress: String
}

type OrderItem @table(key: ["order", "product"]) {
  order: Order!
  product: Product!
  quantity: Int!
  unitPrice: Float!
}